# Decision Tree Classification

## Importing the libraries

In [3]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

## Importing the dataset

In [4]:
dataset = pd.read_csv('Indian Liver Patient Dataset (ILPD).csv', header=None)
m = dataset[9].mean()
dataset[9].fillna(m, inplace = True) 

In [5]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 583 entries, 0 to 582
Data columns (total 11 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   0       583 non-null    int64  
 1   1       583 non-null    object 
 2   2       583 non-null    float64
 3   3       583 non-null    float64
 4   4       583 non-null    int64  
 5   5       583 non-null    int64  
 6   6       583 non-null    int64  
 7   7       583 non-null    float64
 8   8       583 non-null    float64
 9   9       583 non-null    float64
 10  10      583 non-null    int64  
dtypes: float64(5), int64(5), object(1)
memory usage: 50.2+ KB


In [6]:
X = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values
# type(X)

In [7]:
## Encoding categorical data

In [8]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [1])], remainder='passthrough')
X = ct.fit_transform(X)
type(X)

numpy.ndarray

## Splitting the dataset into the Training set and Test set

In [9]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.25, random_state = 0)

## Feature Scaling

In [10]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

## Training the Decision Tree Classification model on the Training set

In [11]:
from sklearn.tree import DecisionTreeClassifier
classifier = DecisionTreeClassifier(criterion = 'entropy', random_state = 0)
classifier.fit(X_train, y_train)

DecisionTreeClassifier(criterion='entropy', random_state=0)

## Making the Confusion Matrix test data

In [12]:
from sklearn.metrics import confusion_matrix, accuracy_score
y_pred = classifier.predict(X_test)
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)
 
# y_pred = classifier.predict(ct.transform([[20,'Male',1.1,0.5,128,20,30,3.9,1.9,0.95]]))
# y_pred[0]

[[78 22]
 [24 22]]


0.684931506849315

## Making the Confusion Matrix  Training data accuracy_score

In [15]:
y_pred1 = classifier.predict(X_train)
cm = confusion_matrix(y_train, y_pred1)
print(cm)
accuracy_score(y_train, y_pred1)

[[316   0]
 [  0 121]]


1.0

In [14]:
y_pred = classifier.predict(X_test)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[[1 1]
 [1 1]
 [1 2]
 [1 1]
 [1 1]
 [2 2]
 [1 1]
 [2 1]
 [1 1]
 [2 1]
 [1 1]
 [1 1]
 [2 1]
 [2 2]
 [1 1]
 [1 1]
 [1 1]
 [1 2]
 [1 1]
 [1 1]
 [1 1]
 [2 2]
 [1 2]
 [1 1]
 [1 1]
 [2 2]
 [1 1]
 [1 1]
 [1 2]
 [1 2]
 [1 1]
 [1 1]
 [2 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [2 1]
 [1 1]
 [1 1]
 [2 1]
 [2 2]
 [1 1]
 [1 1]
 [2 1]
 [1 1]
 [1 1]
 [2 2]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [2 2]
 [1 2]
 [1 2]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [2 2]
 [1 1]
 [2 1]
 [1 1]
 [1 2]
 [2 2]
 [1 2]
 [2 1]
 [1 1]
 [1 1]
 [1 2]
 [2 2]
 [2 2]
 [1 2]
 [2 2]
 [1 1]
 [2 2]
 [1 1]
 [1 1]
 [1 1]
 [1 2]
 [2 2]
 [1 2]
 [2 1]
 [2 1]
 [1 1]
 [1 1]
 [1 1]
 [2 2]
 [1 1]
 [1 1]
 [2 2]
 [1 1]
 [1 1]
 [1 2]
 [2 2]
 [1 1]
 [2 1]
 [1 1]
 [1 2]
 [2 1]
 [1 1]
 [1 1]
 [1 1]
 [1 2]
 [2 2]
 [2 2]
 [2 2]
 [2 1]
 [1 1]
 [2 1]
 [1 2]
 [1 2]
 [1 2]
 [1 2]
 [1 2]
 [1 2]
 [2 1]
 [1 1]
 [2 1]
 [2 2]
 [2 1]
 [1 1]
 [2 1]
 [1 1]
 [2 1]
 [1 1]
 [1 1]
 [2 1]
 [1 1]
 [1 1]
 [2 1]
 [1 1]
 [1 2]
 [1 1]
 [1 1]
 [1 1]
 [2 2]
 [1 1]
 [1 1]