# K-Nearest Neighbors (K-NN)

## Importing the libraries

In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

## Importing the dataset

In [2]:
dataset = pd.read_csv('Indian Liver Patient Dataset (ILPD).csv', header=None)
m = dataset[9].mean()
dataset[9].fillna(m, inplace = True) 
print(dataset.to_string()) 


     0       1     2     3     4     5     6    7    8         9   10
0    65  Female   0.7   0.1   187    16    18  6.8  3.3  0.900000   1
1    62    Male  10.9   5.5   699    64   100  7.5  3.2  0.740000   1
2    62    Male   7.3   4.1   490    60    68  7.0  3.3  0.890000   1
3    58    Male   1.0   0.4   182    14    20  6.8  3.4  1.000000   1
4    72    Male   3.9   2.0   195    27    59  7.3  2.4  0.400000   1
5    46    Male   1.8   0.7   208    19    14  7.6  4.4  1.300000   1
6    26  Female   0.9   0.2   154    16    12  7.0  3.5  1.000000   1
7    29  Female   0.9   0.3   202    14    11  6.7  3.6  1.100000   1
8    17    Male   0.9   0.3   202    22    19  7.4  4.1  1.200000   2
9    55    Male   0.7   0.2   290    53    58  6.8  3.4  1.000000   1
10   57    Male   0.6   0.1   210    51    59  5.9  2.7  0.800000   1
11   72    Male   2.7   1.3   260    31    56  7.4  3.0  0.600000   1
12   64    Male   0.9   0.3   310    61    58  7.0  3.4  0.900000   2
13   74  Female   1.

In [3]:
X = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values
X[1,:]

array([62, 'Male', 10.9, 5.5, 699, 64, 100, 7.5, 3.2, 0.74], dtype=object)

In [4]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [1])], remainder='passthrough')
X = ct.fit_transform(X)
type(X)

numpy.ndarray

In [5]:
# from sklearn.datasets import load_iris
# from sklearn.linear_model import LogisticRegression
# X, y = load_iris(return_X_y=True)

In [6]:
y

array([1, 1, 1, 1, 1, 1, 1, 1, 2, 1, 1, 1, 2, 1, 1, 2, 1, 2, 1, 1, 1, 1,
       1, 1, 2, 1, 1, 1, 2, 2, 1, 1, 2, 2, 2, 1, 2, 1, 1, 1, 1, 2, 2, 1,
       2, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 1, 2, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 2, 1, 1, 1, 1, 1, 2, 1, 1, 2, 1, 1, 1, 2, 1, 1, 1, 2, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 1, 2, 1, 2, 2, 2, 2, 2,
       2, 1, 2, 1, 2, 2, 1, 1, 1, 1, 1, 1, 2, 1, 2, 2, 1, 1, 1, 1, 1, 2,
       2, 1, 1, 1, 1, 1, 1, 1, 2, 1, 1, 1, 1, 2, 1, 1, 1, 1, 2, 1, 1, 2,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 2, 1, 1, 2, 1, 1, 1, 2, 1, 1, 1, 2, 2, 1, 1, 1,
       2, 1, 1, 1, 2, 2, 2, 1, 1, 1, 1, 1, 1, 1, 2, 1, 1, 2, 2, 1, 2, 1,
       1, 1, 1, 2, 1, 1, 1, 1, 2, 1, 2, 1, 1, 1, 1, 1, 2, 1, 2, 1, 2, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 1, 1, 1, 2, 1, 1, 1, 1, 1,
       2, 2, 1, 1, 1, 1, 1, 2, 1, 1, 1, 2, 2, 1, 1, 1, 1, 2, 1, 2, 1, 1,
       1, 2, 1, 1, 1, 2, 1, 2, 1, 1, 1, 2, 1, 2, 2,

## Splitting the dataset into the Training set and Test set

In [7]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.25, random_state = 0)

In [8]:
print(X_train)

[[1.0 0.0 8 ... 7.5 3.4 0.8]
 [0.0 1.0 62 ... 8.2 3.2 0.6]
 [1.0 0.0 65 ... 6.8 2.9 0.7]
 ...
 [1.0 0.0 69 ... 8.4 4.9 1.4]
 [0.0 1.0 60 ... 6.6 3.5 1.1]
 [0.0 1.0 26 ... 7.5 2.6 0.5]]


In [9]:
print(y_train)

[1 2 2 1 1 1 1 1 1 1 1 1 1 2 2 1 1 2 1 1 1 1 2 1 1 1 1 1 2 2 1 1 1 1 1 2 1
 1 1 1 1 2 1 1 1 1 1 1 1 1 1 2 2 1 2 1 1 2 1 1 1 1 1 1 1 1 1 1 2 2 1 1 2 1
 1 2 1 2 1 1 1 1 2 1 1 2 1 1 1 1 1 2 2 1 2 1 1 1 1 2 1 1 1 1 1 1 1 1 1 1 1
 2 1 2 1 1 1 1 2 1 1 1 1 1 2 1 1 1 1 1 1 1 1 2 2 1 1 1 1 2 1 1 1 1 1 2 1 1
 1 1 1 1 1 1 2 2 1 2 1 1 1 1 1 2 2 1 1 2 2 2 1 2 2 2 1 2 1 1 1 1 1 1 1 2 2
 1 1 2 1 1 1 1 1 1 1 1 1 2 1 2 1 1 1 1 1 2 1 1 2 1 1 1 1 1 2 1 1 2 1 2 1 1
 1 1 2 2 2 1 1 1 1 1 1 2 1 1 2 1 2 1 2 1 1 2 1 2 1 1 2 1 1 1 2 1 2 2 2 2 1
 2 1 1 1 1 1 1 1 1 2 1 2 1 2 2 1 1 2 1 1 1 1 1 2 1 1 2 1 2 1 1 1 1 2 1 2 1
 1 1 1 2 1 2 1 1 1 2 1 1 2 1 1 1 2 1 1 1 1 2 1 1 1 2 1 2 1 1 2 1 1 2 2 1 1
 2 1 1 1 2 1 2 2 1 2 1 2 1 1 1 2 1 1 1 1 1 1 1 1 2 1 1 1 1 2 1 1 1 2 2 1 1
 1 1 1 1 1 1 1 2 2 1 1 1 2 1 1 2 1 1 1 2 1 1 2 2 1 1 1 2 1 1 1 2 1 1 1 2 1
 1 2 1 1 1 1 2 1 2 1 1 1 1 2 2 1 1 1 1 2 1 1 1 2 1 1 1 2 1 1]


In [10]:
print(X_test)

[[0.0 1.0 55 ... 6.1 2.7 0.7]
 [0.0 1.0 60 ... 7.4 3.0 0.6]
 [0.0 1.0 38 ... 7.5 4.2 1.2]
 ...
 [0.0 1.0 17 ... 6.9 4.2 1.55]
 [1.0 0.0 58 ... 7.0 4.0 1.3]
 [0.0 1.0 36 ... 6.0 2.2 0.5]]


In [11]:
print(y_test)

[1 1 2 1 1 2 1 1 1 1 1 1 1 2 1 1 1 2 1 1 1 2 2 1 1 2 1 1 2 2 1 1 1 1 1 1 1
 1 1 1 1 1 1 2 1 1 1 1 1 2 1 1 1 1 1 1 2 2 2 1 1 1 1 2 1 1 1 2 2 2 1 1 1 2
 2 2 2 2 1 2 1 1 1 2 2 2 1 1 1 1 1 2 1 1 2 1 1 2 2 1 1 1 2 1 1 1 1 2 2 2 2
 1 1 1 2 2 2 2 2 2 1 1 1 2 1 1 1 1 1 1 1 1 1 1 1 1 2 1 1 1 2 1 1 1 1 2]


## Feature Scaling

In [12]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [13]:
print(X_train)

[[ 1.68325082 -1.68325082 -2.27249983 ...  0.90008585  0.30893012
  -0.47366869]
 [-0.59408853  0.59408853  1.07831565 ...  1.52713268  0.06235028
  -1.09210172]
 [ 1.68325082 -1.68325082  1.26447207 ...  0.27303902 -0.30751948
  -0.7828852 ]
 ...
 [ 1.68325082 -1.68325082  1.51268062 ...  1.70628892  2.1582789
   1.38163038]
 [-0.59408853  0.59408853  0.95421138 ...  0.09388279  0.43222004
   0.45398084]
 [-0.59408853  0.59408853 -1.15556134 ...  0.90008585 -0.67738923
  -1.40131823]]


In [14]:
print(X_test)

[[-0.59408853  0.59408853  0.64395068 ... -0.3540078  -0.55409931
  -0.7828852 ]
 [-0.59408853  0.59408853  0.95421138 ...  0.81050774 -0.18422956
  -1.09210172]
 [-0.59408853  0.59408853 -0.41093567 ...  0.90008585  1.29524947
   0.76319736]
 ...
 [-0.59408853  0.59408853 -1.71403058 ...  0.36261714  1.29524947
   1.84545515]
 [ 1.68325082 -1.68325082  0.8301071  ...  0.45219526  1.04866963
   1.07241387]
 [-0.59408853  0.59408853 -0.53503995 ... -0.44358592 -1.17054891
  -1.40131823]]


## Training the K-NN model on the Training set

In [15]:
from sklearn.neighbors import KNeighborsClassifier
classifier = KNeighborsClassifier(n_neighbors = 5, metric = 'minkowski', p = 2)
classifier.fit(X_train, y_train)

KNeighborsClassifier()

## Predicting a new result

In [16]:
# print(classifier.predict(sc.transform([[30,87000]])))

## Predicting the Test set results

In [17]:
y_pred = classifier.predict(X_test)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[[1 1]
 [1 1]
 [1 2]
 [1 1]
 [1 1]
 [1 2]
 [1 1]
 [1 1]
 [1 1]
 [2 1]
 [1 1]
 [1 1]
 [1 1]
 [1 2]
 [1 1]
 [1 1]
 [1 1]
 [1 2]
 [1 1]
 [1 1]
 [1 1]
 [1 2]
 [1 2]
 [1 1]
 [1 1]
 [2 2]
 [1 1]
 [1 1]
 [1 2]
 [2 2]
 [2 1]
 [1 1]
 [2 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [2 1]
 [1 2]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 2]
 [1 1]
 [2 1]
 [1 1]
 [1 1]
 [1 1]
 [2 1]
 [2 2]
 [2 2]
 [1 2]
 [2 1]
 [1 1]
 [1 1]
 [1 1]
 [2 2]
 [1 1]
 [2 1]
 [1 1]
 [1 2]
 [1 2]
 [1 2]
 [1 1]
 [2 1]
 [1 1]
 [1 2]
 [1 2]
 [1 2]
 [1 2]
 [1 2]
 [2 1]
 [1 2]
 [2 1]
 [1 1]
 [1 1]
 [1 2]
 [1 2]
 [2 2]
 [2 1]
 [2 1]
 [1 1]
 [2 1]
 [1 1]
 [2 2]
 [1 1]
 [1 1]
 [2 2]
 [2 1]
 [1 1]
 [1 2]
 [2 2]
 [1 1]
 [1 1]
 [1 1]
 [1 2]
 [1 1]
 [1 1]
 [1 1]
 [2 1]
 [1 2]
 [1 2]
 [1 2]
 [2 2]
 [1 1]
 [1 1]
 [1 1]
 [1 2]
 [2 2]
 [1 2]
 [2 2]
 [1 2]
 [1 2]
 [1 1]
 [1 1]
 [1 1]
 [1 2]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [2 1]
 [1 1]
 [1 2]
 [1 1]
 [2 1]
 [1 1]
 [2 2]
 [1 1]
 [1 1]

## Making the Confusion Matrix

In [18]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[81 19]
 [33 13]]


0.6438356164383562

## Making the Confusion Matrix  Training data accuracy_score

In [19]:
y_pred1 = classifier.predict(X_train)
cm = confusion_matrix(y_train, y_pred1)
print(cm)
accuracy_score(y_train, y_pred1)

[[281  35]
 [ 61  60]]


0.7803203661327232

## Visualising the Training set results

## Visualising the Test set results