## Importing the libraries

In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

## Importing the dataset

In [2]:
dataset = pd.read_csv('Indian Liver Patient Dataset (ILPD).csv', header=None)
m = dataset[9].mean()
dataset[9].fillna(m, inplace = True) 
print(dataset.to_string()) 

 


     0       1     2     3     4     5     6    7    8         9   10
0    65  Female   0.7   0.1   187    16    18  6.8  3.3  0.900000   1
1    62    Male  10.9   5.5   699    64   100  7.5  3.2  0.740000   1
2    62    Male   7.3   4.1   490    60    68  7.0  3.3  0.890000   1
3    58    Male   1.0   0.4   182    14    20  6.8  3.4  1.000000   1
4    72    Male   3.9   2.0   195    27    59  7.3  2.4  0.400000   1
5    46    Male   1.8   0.7   208    19    14  7.6  4.4  1.300000   1
6    26  Female   0.9   0.2   154    16    12  7.0  3.5  1.000000   1
7    29  Female   0.9   0.3   202    14    11  6.7  3.6  1.100000   1
8    17    Male   0.9   0.3   202    22    19  7.4  4.1  1.200000   2
9    55    Male   0.7   0.2   290    53    58  6.8  3.4  1.000000   1
10   57    Male   0.6   0.1   210    51    59  5.9  2.7  0.800000   1
11   72    Male   2.7   1.3   260    31    56  7.4  3.0  0.600000   1
12   64    Male   0.9   0.3   310    61    58  7.0  3.4  0.900000   2
13   74  Female   1.

In [3]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 583 entries, 0 to 582
Data columns (total 11 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   0       583 non-null    int64  
 1   1       583 non-null    object 
 2   2       583 non-null    float64
 3   3       583 non-null    float64
 4   4       583 non-null    int64  
 5   5       583 non-null    int64  
 6   6       583 non-null    int64  
 7   7       583 non-null    float64
 8   8       583 non-null    float64
 9   9       583 non-null    float64
 10  10      583 non-null    int64  
dtypes: float64(5), int64(5), object(1)
memory usage: 50.2+ KB


In [4]:
X = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values
type(X)

numpy.ndarray

## Encoding categorical data

In [5]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [1])], remainder='passthrough')
X = ct.fit_transform(X)
type(X)

numpy.ndarray

In [6]:
X[1,:]

array([0.0, 1.0, 62, 10.9, 5.5, 699, 64, 100, 7.5, 3.2, 0.74],
      dtype=object)

## Splitting the dataset into the Training set and Test set

In [7]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X[:,2:], y, test_size = 0.2, random_state = 1)
type(X_train)

numpy.ndarray

## Feature Scaling

In [8]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)     # here we are fit the value for train  set and transform 
X_test= sc.transform(X_test)    # here we just transform with train data value because test data set is actualy supries one 

## Training the Logistic Regression model on the Training set

In [9]:
from sklearn.linear_model import LogisticRegression
classifier = LogisticRegression(random_state=0 ).fit(X_train, y_train)
# classifier


In [10]:
from sklearn.metrics import confusion_matrix, accuracy_score
y_pred = classifier.predict(X_test)
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[77  6]
 [24 10]]


0.7435897435897436

## Making the Confusion Matrix  Training data accuracy_score

In [11]:
y_pred1 = classifier.predict(X_train)
cm = confusion_matrix(y_train, y_pred1)
print(cm)
accuracy_score(y_train, y_pred1)

[[305  28]
 [103  30]]


0.7188841201716738

In [12]:
y_pred = classifier.predict(X_test)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[[1 1]
 [1 2]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 2]
 [1 1]
 [1 1]
 [2 2]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 2]
 [1 1]
 [1 1]
 [1 1]
 [2 2]
 [1 1]
 [1 1]
 [1 1]
 [2 2]
 [2 1]
 [2 1]
 [2 1]
 [1 1]
 [2 2]
 [1 2]
 [1 2]
 [1 2]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 2]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 2]
 [1 1]
 [1 2]
 [1 1]
 [1 1]
 [2 2]
 [2 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 2]
 [1 1]
 [1 1]
 [1 1]
 [2 1]
 [2 1]
 [2 2]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 2]
 [1 1]
 [1 1]
 [1 2]
 [2 2]
 [1 1]
 [1 1]
 [2 2]
 [1 1]
 [1 1]
 [1 2]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 2]
 [1 2]
 [1 2]
 [1 2]
 [1 2]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [2 2]
 [1 2]
 [1 1]
 [1 1]
 [1 2]
 [1 1]
 [2 2]
 [1 2]
 [1 1]
 [1 2]
 [1 1]
 [1 2]
 [1 2]
 [1 1]
 [1 1]]
